package:
    name: marching_cubes

  {% if GIT_DESCRIBE_NUMBER|int == 0 %}
    version: {{GIT_DESCRIBE_TAG}}
  {% else %}
    # If we're using a non-tagged revision, append '.postN' to the version
    version: {{GIT_DESCRIBE_TAG}}.post{{GIT_DESCRIBE_NUMBER}}
  {% endif %}

source:
  path: ../

build:
  number: 0
  string: py{{CONDA_PY}}_{{PKG_BUILDNUM}}_h{{PKG_HASH}}_g{{GIT_FULL_HASH[:7]}}

requirements:
  build:
    - cmake
    - {{ compiler("cxx") }}
  host:
    - python {{ python }}
    - boost {{ boost }}
    - pybind11
  run:
    - python
    - boost
    - {{ pin_compatible("numpy") }}

test:
  imports:
    - marching_cubes

about:
  home: http://ilastik.org
  license: BSD (3-clause)
  liscense_file: LICENSE
  summary: A fast marching cubes implementation in C++ with python bindings.
